"""Create `node_index` table.

Phase 2.0: bootstrap the Postgres-backed index used to answer
metadata queries without walking the filesystem.

Revision ID: 0001
Revises:
Create Date: 2026-08-05

Notes:

    - This migration is hand-written (not autogenerated) because:
        (a) The CI environment doesn't have a Postgres available
            at the time migrations are first authored.
        (b) The schema is small and stable, so the duplication
            between model and migration is a feature — readers
            see exactly what the DB knows.
    - Future migrations should keep being hand-written unless
      autogenerate is run against a live DB and the diff is
      reviewed.
    - The CHECK constraint on `node_type` mirrors the
      application-layer enum; adding a NodeType in the future
      requires a migration that updates this constraint.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import func


# revision identifiers, used by Alembic.
revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Create the index table, indexes, and CHECK constraint."""
    op.create_table(
        "node_index",
        sa.Column("node_id", sa.String(36), primary_key=True, nullable=False),
        sa.Column("parent_id", sa.String(36), nullable=True),
        sa.Column("story_id", sa.String(36), nullable=True),
        sa.Column("title", sa.String(512), nullable=False),
        sa.Column("node_type", sa.String(32), nullable=False),
        sa.Column("filesystem_path", sa.String(1024), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=func.now(),
        ),
        sa.Column(
            "search_text",
            sa.String,
            nullable=False,
            server_default="",
        ),
        # Discriminator stays within the closed set the domain
        # currently knows. Adding a NodeType means adding a string
        # here AND updating this CHECK in a follow-up migration.
        sa.CheckConstraint(
            "node_type IN ('story', 'task', 'note')",
            name="ck_node_index_node_type",
        ),
    )

    # Btree indexes for the most common query shapes. FTS column
    # is included even though it's empty in Phase 2.0 — adding a
    # separate tsvector index belongs in the search phase.
    op.create_index("ix_node_index_story_id", "node_index", ["story_id"])
    op.create_index("ix_node_index_parent_id", "node_index", ["parent_id"])
    op.create_index("ix_node_index_search_text", "node_index", ["search_text"])


def downgrade() -> None:
    """Drop `node_index`. Indexes and constraint are removed
    implicitly by dropping the table."""
    op.drop_table("node_index")
